### PR TITLE
Add one more error code for the rvvm_attach_mmio

### PR DESCRIPTION
**Pull request by ghost**
- Introduce new error code: `RVVM_VM_IS_RUNNING_ERR` for the `rvvm_attach_mmio` API function
- Add important information in the `rvvm_attach_mmio`'s documentation.

### CODE REVIEW

**Review by LekKit — APPROVED** [review]

**Comment by X547** [comment]
So no hotplug?

**Comment by ghost** [comment]
> So no hotplug?

What do you mean?

**Comment by X547** [comment]
Ability to add new MMIO devices at runtime when VM is running.

**Comment by ghost** [comment]
> Ability to add new MMIO devices at runtime when VM is running.

Uh, sorry, didn't understood you at the first glance. I'll try to discuss about it with the repository owner.

**Comment by LekKit** [comment]
> So no hotplug?

There may be, but no busses allow such behavior at the moment. We also need to gracefuly park CPU threads before manipulating device lookup list (Easy to do).

MMIO devices are baked into FDT and hardwired to the SoC, PCIe hotplug isn't implemented (yet). Other types of busses (I2C) are OK but they are unrelated to mmio subsystem.

What are your wanted usecases for hotplug? I could think of dynamic drive attach

**Comment by LekKit** [comment]
For testing PCIe hotplug I'd really like to have a working physical board with that, and my VF2 is yet to arrive...

**Pull request merged**
