### PR TITLE
ns16550a: Support different backends

### PR DESCRIPTION
**Pull request by ghost**
WIP for preview and early review if interested, thank you!

- introduce `chardev_t` as ns16550a backend.  OO pattern from https://nullprogram.com/blog/2014/10/21/
- refactorying out terminal backend as `ns16550a_term.c`
- add `ns16550a_tcp.c` backend for testing

Connect as `socat stdio,echo=0,raw tcp:localhost:3000`, multiple clients supported.
Need add a cmd option to select backend, more error handling and cleanup...

### CODE REVIEW

**Comment by LekKit** [comment]
Generally nicely designed but a few caveats:
- You shouldn't include `<unistd.h>` or any OS-specific header outside of `networking.c`/`threading.c`/`blk_io.c`/etc wrappers. I know you wanted to use `ssize_t`, I think it is possible to use `size_t` unless you want a very detailed error handling (Usually there is no point esp. since different backends will be different, and in general it is nice when there is no error other than host-induced which is immediately reported via `rvvm_error()`
- Some build issues in different places, I hope you can resolve them (Or invite me in your repo)
- You are apparently relying on the fact that you can cast `chardev_t*` into pointer to different struct that holds `chardev_t` as a first member. This is a non-portable hack and might break on weird targets like Emscripten. You are better of adding some opaque `void*` pointer as `chardev_t` field and casting it into a pointer to `*some backend-defined struct*`
- Rename other term implementations to `chardev_term.c`, `chardev_tcp.c` because they have nothing to do with NS16550 (There are other types of uarts etc etc)

There are things that need some questions and possible redesign:
- Earlier polling implementation is possibly sub-ideal and I'd want a way to call back into UART and explicitly send an interrupt, because I'll be running a separate terminal thread for proper event-driven approach. This asks for a bit of redesign to `chardev_t` api
- Shouldn't different TCP connections work with different UARTs? Or, there should be multiple ports per each UART instead?

**Comment by ghost** [comment]
> Generally nicely designed but a few caveats:

Thanks, this is very help for me!

 
> * You shouldn't include `<unistd.h>` or any OS-specific header outside of `networking.c`/`threading.c`/`blk_io.c`/etc wrappers. I know you wanted to use `ssize_t`, I think it is possible to use `size_t` unless you want a very detailed error handling (Usually there is no point esp. since different backends will be different, and in general it is nice when there is no error other than host-induced which is immediately reported via `rvvm_error()`

Okay, make sense.


> * Some build issues in different places, I hope you can resolve them (Or invite me in your repo)

some `USE_NET` conditions, yeah I can fix it later..

> * You are apparently relying on the fact that you can cast `chardev_t*` into pointer to different struct that holds `chardev_t` as a first member. This is a non-portable hack and might break on weird targets like Emscripten. You are better of adding some opaque `void*` pointer as `chardev_t` field and casting it into a pointer to `*some backend-defined struct*`

Well, I find this in c99 spec https://www.open-std.org/jtc1/sc22/WG14/www/docs/n1256.pdf   6.7.2.1 13:
```
A pointer to a structure object, suitably converted, points to its initial member (or if that member is a
bit-field, then to the unit in which it resides), and vice versa. There may be unnamed
padding within a structure object, but not at its beginning.
```
Which should be safe IIUC, but I don't know about Emscripten, so I modify thoes to use a `void* userdata` pointer.


> * Rename other term implementations to `chardev_term.c`, `chardev_tcp.c` because they have nothing to do with NS16550 (There are other types of uarts etc etc)

Okay.

> There are things that need some questions and possible redesign:
> 
> * Earlier polling implementation is possibly sub-ideal and I'd want a way to call back into UART and explicitly send an interrupt, because I'll be running a separate terminal thread for proper event-driven approach. This asks for a bit of redesign to `chardev_t` api

I'm not sure how to implement it, does every `chardev_t` has its thread looping with select/poll and call a callback from uart?

> * Shouldn't different TCP connections work with different UARTs? Or, there should be multiple ports per each UART instead?

Multiple ports should works.

I also add a `chardev_mux` to combine two chardev_t as one, so term and tcp can show a uart session sync..

**Comment by ghost** [comment]
> Earlier polling implementation is possibly sub-ideal and I'd want a way to call back into UART and explicitly send an interrupt, because I'll be running a separate terminal thread for proper event-driven approach. This asks for a bit of redesign to chardev_t api

Okay, I think I got a suitable api, inspired from `hid_dev.h` and `tap_linux.c`:
```
#ifndef CHARDEV_H
#define CHARDEV_H

#include "rvvmlib.h"

typedef struct chardev chardev_t;

typedef struct {
    void on_input_available(chardev_t* dev);
    void on_output_available(chardev_t* dev);
    void* userdata;
} chardev_watcher_t;

struct chardev {
    size_t (*read)(void* buf, size_t nbytes, void* userdata);
    size_t (*write)(const void* buf, size_t nbytes, void* userdata);
    void (*destroy)(void* userdata);
    chardev_watcher_t* watcher;
    void* userdata;
};

static inline size_t chardev_read(chardev_t* dev, void* buf, size_t nbytes)
{
    return dev->read(buf, nbytes, dev->userdata);
}
static inline size_t chardev_write(chardev_t* dev, const void* buf, size_t nbytes)
{
    return dev->write(buf, nbytes, dev->userdata);
}
static inline void chardev_destroy(chardev_t* dev)
{
    return dev->destroy(dev->userdata);
}
static inline void chardev_input_available(chardev_t* dev)
{
    return dev->watcher->on_input_available(dev);
}
static inline void chardev_output_available(chardev_t* dev)
{
    return dev->watcher->on_output_available(dev);
}

#endif
```

A `term` or `tcp` chardev can create a thread to do select/poll loop, notify the watcher (ns16550a or chardev_mux) by `chardev_input_available` and `chardev_output_available`.

One problem I now have is to shutdown/thread_join the loop of `chardev_term`, does a `pipe` (I see in `tap_linux.c` , `poll` is shutdown by a `pipe`) suitable to shutdown the POSIX `select` loop?  How about Windows?

For `chardev_tcp`, I guess `net_poll_close` is enough.

WDYT, thank you!

**Comment by LekKit** [comment]
> One problem I now have is to shutdown/thread_join the loop of `chardev_term`, does a `pipe` (I see in `tap_linux.c` , `poll` is shutdown by a `pipe`) suitable to shutdown the POSIX `select` loop? How about Windows?

For `chardev_tcp`, look at `tap_user` and how it uses `net_tcp_sockpair()`. It creates a local socket pair - basically a portable `pipe()` on anything that has sockets.

For `chardev_term`, the terminal thread killing implementation is likely to be very obscure, as all things under Windows. I am fine if you don't want to handle it properly right now and you may continue using a sleep-poll loop under Windows till I come with a better solution. You may also add a `update()` call sorta to the chardev interface because it's possible there is no other way on Windows...

**Comment by LekKit** [comment]
> For `chardev_tcp`, I guess `net_poll_close` is enough.

Maybe, but be cautious (This wasn't tested well). Thing is, `net_poll_close()` frees a `net_poll_t*` pointer and if you do anything to it from another thread afterwards you have a UAF and other nasty consequences. 

As I already said a sockpair is a much cleaner and better approach than RCU madness and guessing if each of `net_poll` implementations acts well upon closing with waiters on it.

**Comment by ghost** [comment]
Hello, thank you for the tips.  Now it can shutdown properly, yet there are still issues I know:
- The term and tcp thread consume 100% cpu, it seems when polling the output is always available, or if input available but not consumed, then the loop will call callbacks to waste cpu..  Should we add a sleep here, at what interval?
- When a tcp client is disconnected, its sock won't pop from net_poll_wait immediately, only when try to write to it.  I think this is not a big deal..

Also I'm bad at naming things, feel free to suggest alternative names or api structures, or make changes by your pace.

**Comment by LekKit** [comment]
> * The term and tcp thread consume 100% cpu, it seems when polling the output is always available, or if input available but not consumed, then the loop will call callbacks to waste cpu..  Should we add a sleep here, at what interval?

There needs to be more logic concerning "input available but the guest haven't looked yet" and "output is available but we do not care"
Generally you should poll for input, and then remove it from watch set until the guest empties the input buffer and `read(stdin)` returns 0. So basically edge-triggered input availability detection sorta.
Polling for output availability should only happen if the guest enabled the "TX" interrupt, and also should be edge-triggered (Reset only after a write).

> * When a tcp client is disconnected, its sock won't pop from net_poll_wait immediately, only when try to write to it.  I think this is not a big deal..

What do you mean? You want to know how to detect a disconnect?
Disconnected clients always post an event, and when you `recv()` or `send()` on them, you get 0 in return. It is a sign of a socket disconnect. Example:

```cpp
ev_count = net_poll_wait(poll, events, NET_POLL_INF);
for (size_t i=0; i<ev_count; ++i) {
    net_sock_t* sock = // some way to get socket from events[i].data context
    size_t received = net_tcp_recv(sock, ...);
    if (!received) {
        // this client has disconnected!
    }
}
```

**Comment by LekKit** [comment]
> Also I'm bad at naming things, feel free to suggest alternative names or api structures, or make changes by your pace.

I am just a bit overwhelmed by the things going on :D, and I am always asking you to change some stuff.. Because I am afraid of possible merge conflicts or sth, or just don't like disturbing people in general.

I need to do 1 simple change to `ns16550a.c` upstream, actually include `<sys/select.h>` because on Serenity it is not automatically included elsewhere and it raises a warning. May I do this? You'll need to rebase

Another thing that I'd like to be changed in current chardev design. It is manually freed, but all the current RVVM devices have a notion of `remove()` callback and are automatically freed when the owning VM is destroyed. This significantly simplifies memory management for library user, and keeps RVVM leak-free fool-proof.
I'd like that `ns16550a_remove()` calls `chardev_free()` so they are freed together.

**Comment by ghost** [comment]
> Generally you should poll for input, and then remove it from watch set until the guest empties the input buffer and read(stdin) returns 0. So basically edge-triggered input availability detection sorta.

Cool, so this is what edge-triggered mean, I'll try it.

> You'll need to rebase
No problem for me :)

> I'd like that ns16550a_remove() calls chardev_free() so they are freed together.
Got it.

I'll keep going according the advices and back here later, thank you!

**Comment by ghost** [comment]
@LekKit Hello, I have get the terminal backend working with a event-driven interface.

- edge-triggered is emulated by manipulate fd_sets via a pipe `ctl` (or atomic bits on windows).
- on windows, the terminal_thread is a loop with `sleep_ms(1)`, since I find no way to select for stdio..
- output callback is enabled only when the `THR` inturrupt is needed, and it can be changed between enabled and disabled.  So `chardev_watch` can be called multiple times.
- no buffer implemented now, so `select` may wake up for each char read/write, I think this can be improved later..

I'd postpone the code for chardev_tcp now, maybe for the android terminal, a `posix_openpt` implemented pseudo-terminal device is better?  @fish4terrisa-MSDSM

**Comment by fish4terrisa-MSDSM** [comment]
> @LekKit Hello, I have get the terminal backend working with a event-driven interface.
> 
> * edge-triggered is emulated by manipulate fd_sets via a pipe `ctl` (or atomic bits on windows).
> * on windows, the terminal_thread is a loop with `sleep_ms(1)`, since I find no way to select for stdio..
> * output callback is enabled only when the `THR` inturrupt is needed, and it can be changed between enabled and disabled.  So `chardev_watch` can be called multiple times.
> * no buffer implemented now, so `select` may wake up for each char read/write, I think this can be improved later..
> 
> I'd postpone the code for chardev_tcp now, maybe for the android terminal, a `posix_openpt` implemented pseudo-terminal device is better? @fish4terrisa-MSDSM

Hmm,a pty device is better so that I dont need to run the `resize` command(included in the xterm package) to correct the size of the terminal.

**Comment by fish4terrisa-MSDSM** [comment]
> @LekKit Hello, I have get the terminal backend working with a event-driven interface.
> 
> * edge-triggered is emulated by manipulate fd_sets via a pipe `ctl` (or atomic bits on windows).
> * on windows, the terminal_thread is a loop with `sleep_ms(1)`, since I find no way to select for stdio..
> * output callback is enabled only when the `THR` inturrupt is needed, and it can be changed between enabled and disabled.  So `chardev_watch` can be called multiple times.
> * no buffer implemented now, so `select` may wake up for each char read/write, I think this can be improved later..
> 
> I'd postpone the code for chardev_tcp now, maybe for the android terminal, a `posix_openpt` implemented pseudo-terminal device is better? @fish4terrisa-MSDSM

I have just tried the patch and it didn\`t work .The size of the tty is still wrong...a `posix_openpt` implemented pty might work better,but I\`m not so sure.(Sorry for my poor English)

**Comment by fish4terrisa-MSDSM** [comment]
The terminal just looks like this,and i have to run `resize` to fix the size.
Screenshot_20230428_200216

**Comment by fish4terrisa-MSDSM** [comment]
And connect the terminal on tcp might prevent the user from start multiple VMs, or they have to choose port. Maybe unix socket might be better for unix-like ports? (The path to the unix socket file tells the usage of it, but a tcp port can\`t)

**Comment by ghost** [comment]
@fish4terrisa-MSDSM 
> I have just tried the patch and it didn`t work .The size of the tty is still wrong...

Well, it seems the serial term have to be resized manual, see:
https://wiki.archlinux.org/title/Working_with_the_serial_console#Resizing_a_terminal
https://unix.stackexchange.com/questions/106644/how-to-change-the-width-of-remote-serial-console

> a posix_openpt implemented pty might work better,but I`m not so sure.

Okay, now I see your code use pty with rvvm stdio in `https://github.com/fish4terrisa-MSDSM/archriscv-term/blob/flyingfish/archriscv-app/app/src/main/jni/terminal_jni.c`.
I think a `posix_openpt` backend for rvvm serial can add support of multiple ttys to it.


> And connect the terminal on tcp might prevent the user from start multiple VMs, or they have to choose port. Maybe unix socket might be better for unix-like ports

Yes, use a tcp socket will need more works for ports..  and a unix socket backend should work similiar to pty.

**Comment by LekKit** [comment]
> Hmm,a pty device is better so that I dont need to run the `resize` command(included in the xterm package) to correct the size of the terminal.

The UART tty is not auto-resizable at all because the guest (Linux) has no way to know the remote console was resized (An X terminal emulator would send a `SIGWINCH` signal, but no such signal facility over the UART.

You may add `resize` as a boot service, but repeated changes to the TTY size would require polling it from the guest.

It is theoretically possible to send some VT escapes into the guest to signal the new console size, but most likely will require some guest interoperation still. SSH is our best bet(?)

**Comment by fish4terrisa-MSDSM** [comment]
> > Hmm,a pty device is better so that I dont need to run the `resize` command(included in the xterm package) to correct the size of the terminal.
> 
> The UART tty is not auto-resizable at all because the guest (Linux) has no way to know the remote console was resized (An X terminal emulator would send a `SIGWINCH` signal, but no such signal facility over the UART.

Ok, i will try to find a way to resize the terminal when boot the system.

**Comment by fish4terrisa-MSDSM** [comment]
> 
> Okay, now I see your code use pty with rvvm stdio in `https://github.com/fish4terrisa-MSDSM/archriscv-term/blob/flyingfish/archriscv-app/app/src/main/jni/terminal_jni.c`. I think a `posix_openpt` backend for rvvm serial can add support of multiple ttys to it.
> 
I just borrowed these codes from alpine-term,and i dont\`t know much about it .The only things i know is that it gets the stdio of the program and link it to a terminal.I will work out what these codes have done later.However , I think opening new terminals and run `socat` inside it to connect to sockets which binded to serial ttys  is a easier choice.(Thats the method I used to support multiple ttys for QEMU)

**Comment by fish4terrisa-MSDSM** [comment]
> > Hmm,a pty device is better so that I dont need to run the `resize` command(included in the xterm package) to correct the size of the terminal.
> 
> The UART tty is not auto-resizable at all because the guest (Linux) has no way to know the remote console was resized (An X terminal emulator would send a `SIGWINCH` signal, but no such signal facility over the UART.
> 
> You may add `resize` as a boot service, but repeated changes to the TTY size would require polling it from the guest.
> 
I have tried adding it as a systemd service ,but it don\`t work .Adding it to the bashrc or inside `/etc/profile.d/`might be a good idea(?)
> It is theoretically possible to send some VT escapes into the guest to signal the new console size, but most likely will require some guest interoperation still. SSH is our best bet(?)
SSH might work , but that method have some performance cost (I have tried it with QEMU, it\`s a bit slow and randomly the connection breaks down)

**Comment by LekKit** [comment]
The current implementation is good enough to be in `staging`, but afterwards I will do some tiny changes (rewrite win32 console and maybe slight refactoring). Afterwards we will decide what to do with PTY/TCP chardevs, they will be a separate PR if anything

Are you OK with merging it for now? The discussion here may move to actual discussions or to issue #86

**Comment by ghost** [comment]
> Are you OK with merging it for now? The discussion here may move to actual discussions or to issue #86

Yes, thank you!  And next I'll work on a libretro port and tcp/pty/libvterm chardev backends.

**Comment by LekKit** [comment]
FYI about win32:
- `putc()` is very slow on Windows, but `WriteConsoleW()` is faster (However the Windows console is still very slow in general). It needs UTF16 strings, but UART will feed individual bytes so I have to buffer them and do streaming UTF8 conversion.
- It might be wise to buffer all output bytes and output them via the chardev IO thread instead. This way we eliminate the individual per-character syscalls and prevent the guest CPU stalls (This is currently the case on v0.5, and this effect is enough to slow down guest Linux boot by ~5 seconds on Windows host)

**Comment by LekKit** [comment]
Okay, some more news:
- Changing `chardev_term` read/write to operate on a userspace FIFO ring instead of syscalls directly, and doing IO in whatever separate thread gives HUGE boost to uart speed (But requires a lot of rewrite)
- Went too far with the refactoring and we now may reuse `update` callbacks in chardev API if we don't wish to use a separate thread (It seems that a dedicated uart IO thread is a bit of an overkill idea from me for a lot of usecases (win32), sorry!)

Will be pushing this soon but if anyone doesn't like what I did, I will gladly listen to figure the best way collaborately

**Pull request merged**
